spring:
  application:
    name: spring-jdbc-template
  datasource:
    url: jdbc:mysql://localhost:3306/appdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver