spring:
  application:
    name: spring-jdbc-template
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/appdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:database/schema.sql
    data: classpath:database/data.sql
    initialization-mode: always